# Generated by Django 3.2.20 on 2023-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='schedudled_date_time',
            new_name='scheduled_date_time',
        ),
    ]
